language: ruby
rvm:
  - 2.3.1
sudo: false
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html --disable-external --empty-alt-ignore --assume-extension --url-ignore '/releases\/(release|current).*\//'
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
