# Site settings
title: ELKI Data Mining Framework
email: elki@dbs.ifi.lmu.de
description: >
  Open-Source Data Mining with Java.
baseurl: ""
url: "http://elki-project.github.io"
github_username:  elki-project

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
sass:
  compress: true
compress_html:
  clippings: all #[div, p, ul, ol, li, aside, nav, footer, article, tr, td, dd, dt h1, h2]
  comments: ["<!-- ", " -->"]
  blanklines: true
